# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
# "$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
# dark  = "thinkpad-red-oled"
# dark  = "vscode-dark-modern"
# dark = "nord"
dark = "monokai"
# dark = "tokyo-night"
# dark = "bluloco-dark"
# : }}}
	
[git]
modified  = { fg = "#E2C08D" }
added     = { fg = "#81B88B" }
untracked = { fg = "#73C991" }
deleted   = { fg = "#C74E39" }
updated   = { fg = "#E4676B" }
ignored   = { fg = "#8C8C8C" }
unknown   = { fg = "#8C8C8C" }

modified_sign  = "M "
added_sign     = "A "
untracked_sign = "U "
deleted_sign   = "D "
updated_sign   = "M "
ignored_sign   = "I "
clean_sign     = ""
unknown_sign   = ""
