return {
  -- "goolord/alpha-nvim",
  -- dependencies = { 'nvim-tree/nvim-web-devicons' },
  -- config = function()
  --   local alpha = require("alpha")
  --   local dashboard = require("alpha.themes.dashboard")
  --
  --   -- Set header and buttons
  --   dashboard.section.header.val = {
  --     "                                                     ",
  --     "  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗ ",
  --     "  ████╗  ██║██╔════╝██╔═══██╗██╗   ██║██║████╗ ████║ ",
  --     "  ██╔██╗ ██║█████╗  ██║   ██║██╗   ██║██║██╔████╔██║ ",
  --     "  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║ ",
  --     "  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║ ",
  --     "  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝ ",
  --     "                                                     ",
  --   }
  --   dashboard.section.buttons.val = {
  --     dashboard.button("e", "  New file", ":ene <BAR> startinsert<CR>"),
  --     dashboard.button("f", "  Find file", ":Telescope find_files<CR>"),
  --     dashboard.button("r", "  Recent files", ":Telescope oldfiles<CR>"),
  --     dashboard.button("t", "  Find text", ":Telescope live_grep<CR>"),
  --     dashboard.button("c", "  Configuration", ":e $MYVIMRC<CR>"),
  --     dashboard.button("q", "  Quit Neovim", ":qa<CR>"),
  --   }
  --   dashboard.section.footer.val = "Welcome back!"
  --
  --   -- Set the layout for the dashboard
  --   dashboard.config.layout = {
  --     { type = 'padding', val = 2 },
  --     dashboard.section.header,
  --     { type = 'padding', val = 2 },
  --     dashboard.section.buttons,
  --     { type = 'padding', val = 1 },
  --     dashboard.section.footer,
  --   }
  --
  --   -- Setup alpha
  --   alpha.setup(dashboard.config)
  --
  -- end,
}
